version: '3.8'

services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: cypTrade
    restart: unless-stopped
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./config.json:/freqtrade/config.json"
      - "./freqtrade_hyperopt.json:/freqtrade/freqtrade_hyperopt.json"
    environment:
      - FREQTRADE_CONFIG=/freqtrade/config.json
    command: >
      trade
      --config /freqtrade/config.json
      --strategy SampleStrategy
      --logfile /freqtrade/user_data/logs/freqtrade.log
    ports:
      - "8080:8080"  # API Server
    networks:
      - freqtrade

  freqtrade-api:
    image: freqtradeorg/freqtrade:stable
    container_name: cypTrade-api
    restart: unless-stopped
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./config.json:/freqtrade/config.json"
    environment:
      - FREQTRADE_CONFIG=/freqtrade/config.json
    command: >
      trade
      --config /freqtrade/config.json
      --strategy SampleStrategy
      --api-server
      --api-server-listen-address 0.0.0.0
      --api-server-port 8080
    ports:
      - "8080:8080"
    networks:
      - freqtrade

  freqtrade-backtest:
    image: freqtradeorg/freqtrade:stable
    container_name: cypTrade-backtest
    restart: "no"
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./config.json:/freqtrade/config.json"
    environment:
      - FREQTRADE_CONFIG=/freqtrade/config.json
    command: >
      backtesting
      --config /freqtrade/config.json
      --strategy SampleStrategy
      --timerange 20231201-20231231
    networks:
      - freqtrade

networks:
  freqtrade:
    driver: bridge
