# Docker Compose pour production

services:
  freqtrade:
    build: .
    container_name: cypTrade
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET=${BINANCE_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - FREQTRADE_API_SERVER_LISTEN_IP=0.0.0.0
      - FREQTRADE_API_SERVER_LISTEN_PORT=8080
    volumes:
      - ./user_data:/app/user_data
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    command: freqtrade trade --config config-test.json --strategy SampleStrategy

  # Service pour le monitoring (optionnel)
  monitoring:
    image: prom/prometheus:latest
    container_name: freqtrade-monitoring
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    profiles:
      - monitoring
